### ISSUE TITLE
issue when starting

### ISSUE THREAD

**Issue by selbstmord** [DarkGuy10/BotClient#1]
```
app.on('ready', () => {
    ^
TypeError: Cannot read properties of undefined (reading 'on')
    at Object.<anonymous> (C:\Users\Tayhay\Desktop\BotClient-0.2.0-alpha\index.js:14:5)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m
```

any idea why

**Comment by aiko-chan-ai** [comment]
npm install electron --save-dev
try this

**Comment by selbstmord** [comment]
> 
> 
> npm install electron --save-dev try this

same thing :/

**Comment by DarkGuy10** [comment]
@aiko-chan-ai @selbstmord Im sorry for the late reply but you need to run it using a nightly release of electron
try this:
```
npm install -g electron-nightly
electron . #run this inside BotClient folder
```

**Comment by selbstmord** [comment]
> @aiko-chan-ai @selbstmord Im sorry for the late reply but you need to run it using a nightly release of electron try this:
> 
> ```
> npm install -g electron-nightly
> electron . #run this inside BotClient folder
> ```

unfortunately getting this now

```
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\Tayhay\Desktop\BotClient-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:244:15)
    at async Client.login (C:\Users\Tayhay\Desktop\BotClient-main\node_modules\discord.js\src\client\Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
```

https://i.imgur.com/m5MOTQi.png

**Comment by voltrare** [comment]
@selbstmord 
![image](https://user-images.githubusercontent.com/30526233/143333674-9fa23809-29c9-41ed-a35e-ad292dde3932.png)
enable this

**Comment by DarkGuy10** [comment]
@selbstmord you'll need to enable privileged intents for your bot
Do what @voltrare said
_also, join the support server [invite](https://discord.gg/aZSrxwNUFD)_
