### ISSUE TITLE
[BUG] Discord Client crashes upon opening channel

### ISSUE THREAD

**Issue by ipxter** [DarkGuy10/BotClient#16]
**Describe the bug**
Upon selecting a channel specific channel, the Discord client greys out and the entire user interface disappears

**To Reproduce**
1. Click on the channel
2. Not certain as to why it happens, probably a weird message in the channel cannot be loaded and causes the client to crash

**Expected behavior**
The channel is supposed to open and display the messages

**Screenshots**
![image](https://user-images.githubusercontent.com/56973869/152650427-49b401aa-6343-45d6-8b45-5a63e0004db2.png)
![image](https://user-images.githubusercontent.com/56973869/152650474-4614c2a2-bb0c-4a38-b378-2c7bd9dc6447.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Node version v16.13.2

**Comment by DarkGuy10** [comment]
@all-contributors please add @ipxter for bug
