### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by LolekLiam** [DarkGuy10/BotClient#2]
already installed electron with npm install electron and with npm install electron --save-dev
here is error:

C:\Users\Liam\Downloads\BotClient-0.2.0-alpha\index.js:14
app.on('ready', () => {
    ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (C:\Users\Liam\Downloads\BotClient-0.2.0-alpha\index.js:14:5)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

**Comment by DarkGuy10** [comment]
> @DarkGuy10 how to fix this?

holy shit, why didnt i get notifs for these issues
anyways, like i said for the other issue, you need `electron-nightly` instead of electron (since electron isnt compatible with node 16.6+)
