### ISSUE TITLE
[BUG] Installation problems

### ISSUE THREAD

**Issue by MP3Martin** [DarkGuy10/BotClient#24]
**Describe the bug**
I can not properly install this.

**To Reproduce**
1. Clone and cd into it
2. Run `yarn`
3. I get [this](https://pastebin.com/hUB1n5Ur)
4. I run `yarn start`
5. I get [this](https://pastebin.com/fcapbr1R)
6. The app loads, but when i enter token, it says "**Request to use token, but token was unavailable to the client.**"

**Expected behavior**
It just works

**Screenshots**
Not needed, the would not help.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Node version: v16.7.0

**Additional context**
`yarn -v`: 3.1.1
Had same problems when used old yarn

**Comment by DarkGuy10** [comment]
@MP3Martin update your node version to 17.x (the current one)
Also, I havent tested yarn 2, but the old yarn works fine for the project
My closest guess is, that maybe an issue with wrongly edited appdata
delete your `~/home/.config/botclient` folder and run the app again

**Comment by DarkGuy10** [comment]
welp, seems this issue has died
