### ISSUE TITLE
Can't login without enabling intents!

### ISSUE THREAD

**Issue by karimawii** [DarkGuy10/BotClient#27]
Whenever I login it says:
[DISALLOWED_INTENTS] Privileged intent provided is not enabled or whitelisted. 

But my bot is verified and I can't enable intents, I must apply for them, but I should be able to use the client just fine without intents, I'll be missing some features but it'll mostly work, how can I do that?

**Comment by DarkGuy10** [comment]
@karimawii Yes, you can use the client without a few privileged intents and it should still work, though with some missing features.
Edit `public/electron.js` and comment out either or both of `lines 107 and 108` likes this, depending on whatever intents you can't enable:
![image](https://user-images.githubusercontent.com/62807269/155430349-fa649456-9805-45b8-9a22-75903f74b384.png)

**Comment by karimawii** [comment]
There's no solution for the app version? I must use the source code for that? Cause I have no idea how to set it up from the source code 😢

**Comment by jerbear2008** [comment]
There is not at the moment.

**Comment by DarkGuy10** [comment]
@karimawii there isnt any direct solution for the compiled app at the moment.
You will have to edit from the source code.

**Comment by karimawii** [comment]
Well, thanks for the help, appreciate it

**Comment by DarkGuy10** [comment]
@karimawii you can join our support server and we'll help you out with setting up the source code
