### ISSUE TITLE
[FEATURE] Adding ability to scroll up to more messages

### ISSUE THREAD

**Issue by ducanh2002123** [DarkGuy10/BotClient#33]
**Is your feature request related to a problem? Please describe.**
Currently, the client can only view like 1-2 pages of message, and that's not exactly ideal, since for that little amount of message, not much can actually be done, beside trying to "catch up" with the last chat topic
**Describe the solution you'd like**
Adding the ability to scroll to like messages from 2 weeks ago (API limitation, I believe) would comes in very handy
**Describe alternatives you've considered**
None is found
**Additional context**

**Comment by DarkGuy10** [comment]
This has been in our to-add for a while, and yes there are API limitations so it has to be limited to 2 weeks at max.
I'll keep this issue open till this feature has been added.

**Comment by DarkGuy10** [comment]
Added in [`d7d9e2a`](https://github.com/DarkGuy10/BotClient/commit/d7d9e2a4456648f68aff8b06d97817176d984dd0)
