### ISSUE TITLE
[FEATURE] essages and some other features

### ISSUE THREAD

**Issue by aiko-chan-ai** [DarkGuy10/BotClient#37]
hi bro, i tried your botclient and have some feature request, i think you can do it :)
1. I found this to be a basic html file with some nice features, embedable and some pretty accurate emojis
https://github.com/ItzDerock/discord-html-transcripts/blob/master/src/template.html
2. I also wish it had more features like lightcord or discord-bot-client

**Comment by aiko-chan-ai** [comment]
sr I pressed enter twice

**Comment by DarkGuy10** [comment]
> hi bro, i tried your botclient and have some feature request, i think you can do it :)
> 
>     1. I found this to be a basic html file with some nice features, embedable and some pretty accurate emojis
>        https://github.com/ItzDerock/discord-html-transcripts/blob/master/src/template.html
> 
>     2. I also wish it had more features like lightcord or discord-bot-client

1. for practical purposes, I'll stick to [@skyra-project/discord-components](https://github.com/skyra-project/discord-components/) for now
2. I do intend to add features from Flam3rboy's bot client, and probably later on from lightcord
