### ISSUE TITLE
[FEATURE] SERVEIR LIST

### ISSUE THREAD

**Issue by Sunkwii** [DarkGuy10/BotClient#41]
Put the servers in order of more members to less members and why not add the number of members in the title

**Comment by jerbear2008** [comment]
Could you send this in the feature-request channel in the Discord server? We can discuss it easier there.

**Comment by DarkGuy10** [comment]
> Put the servers in order of more members to less members 

I don't see how that will be of any practical use

> and why not add the number of members in the title

We'll add it alongwith the server settings, not with the title

**Comment by DarkGuy10** [comment]
stale issue
