### ISSUE TITLE
Feature: Copy IDs of various resources

### ISSUE THREAD

**Issue by thegu5** [DarkGuy10/BotClient#54]
### Issue checklist

- [X] I have searched the existing issues to make sure this isn't a duplicate.
- [ ] I have discussed this feature on the support server.

### Feature description

I'd love to have a method to copy the ids of things such as servers, users, and messaages (links not ids).

### Ideal solution or implementation

Have a context menu on right-click, with 'Copy ID' as an option.

### Alternate solution or implementation

If a context menu isn't possible, then right-clicking could copy to clipboard and send a notification.

**Comment by DarkGuy10** [comment]
Context menu API has been added and will be implemented along the line with servers and users too.
